#pragma once
#define DNSCORE_HAS_TSIG_SUPPORT 1
#define DNSCORE_HAS_RDTSC 0
#define DNSCORE_HAS_ACL_SUPPORT 1
#define DNSCORE_HAS_NSEC3_SUPPORT 1
#define DNSCORE_HAS_NSEC_SUPPORT 1
#define DNSCORE_HAS_ZALLOC_SUPPORT 1
#define DNSCORE_HAS_ZALLOC_DEBUG_SUPPORT 0
#define DNSCORE_HAS_NSID_SUPPORT 1
#define DNSCORE_HAS_ZALLOC_STATISTICS_SUPPORT 0
#define DNSCORE_HAS_MALLOC_DEBUG_SUPPORT 0
#define DNSCORE_HAS_MUTEX_DEBUG_SUPPORT 0
#define DNSCORE_HAS_MEMALIGN_ISSUES 0
// version 2.3.0.0-7548
#define DNSCORE_VERSION 0x020300001d7cLL// include/dnscore/dnscore-config-features.h

