#pragma once
#define ZDB_HAS_RRCACHE_ENABLED 0
#define ZDB_HAS_DNSSEC_SUPPORT 1
#define ZDB_HAS_NSEC_SUPPORT 1
#define ZDB_HAS_NSEC3_SUPPORT 1
#define ZDB_HAS_ACL_SUPPORT 1
#define ZDB_HAS_TSIG_SUPPORT 1
#define ZDB_HAS_NSID_SUPPORT 1
#define ZDB_HAS_MUTEX_DEBUG_SUPPORT 0
// version 2.3.0.0-7548
#define DNSDB_VERSION 0x020300001d7cLL// include/dnsdb/zdb-config-features.h

