#pragma once
#define ZDB_HAS_RRCACHE_ENABLED 0
#define ZDB_HAS_DNSSEC_SUPPORT 1
#define ZDB_HAS_NSEC_SUPPORT 1
#define ZDB_HAS_NSEC3_SUPPORT 1
#define ZDB_HAS_ACL_SUPPORT 1
#define ZDB_HAS_TSIG_SUPPORT 1
#define ZDB_HAS_NSID_SUPPORT 1
#define ZDB_HAS_MUTEX_DEBUG_SUPPORT 0
// version 2.3.1.0-7546
#define DNSDB_VERSION 0x020301001d7aLL// include/dnsdb/zdb-config-features.h

